### ISSUE TITLE
Memory leak in MDIManager on caching MDIManagerEvent

### ISSUE THREAD

**Issue by nicoulaj** [flex-users/flexlib#185]
Originally filed by bruno.ba...@gmail.com on 2009-01-08T09:01:41

What steps will reproduce the problem?
1. Make an application that dynamically adds and removed MDIWindows to a 
MDICanvas
2. Use the Flex profiler to monitor the memory
3. You will see that the windows are not garbage collected after they are 
closed (even when you trigger garbage collection using the profiler). The 
reason is that the MDIManagerEvents are cached to send an event when the 
corresponding Effect has finished and they keep a link to the involved 
window(s). These cached instances are removed from the collection when the 
effect sends the EffectEvent.EFFECT_END. However, for some effects there 
are no effect instances and as such the EffectEvent.EFFECT_END is never 
dispatched.
To "fix" this memory leak, the executeDefaultBehavior method should only 
add the mgrEvent to the cache after the effect has been started and there 
are instances created (see attached patch file).

What is the expected output? What do you see instead?
Expected output is that the windows are garbage collected some time after 
they have been closed. They are not.

What version of the product are you using? On what operating system?
Working on the latest version from the SVN repository (the event cache has 
been introduced in MDIManager.as rev. 512

Please provide any additional information below.

**Comment by nicoulaj** [comment]
Updated by bruno.ba...@gmail.com on 2009-01-08T09:06:14

hmm, typo : the revision of MDIManager.as that introduced the event cached is rev 152

**Comment by nicoulaj** [comment]
Updated by dmcc...@gmail.com on 2009-01-08T18:15:09

Added label FlexLib-MDI

**Comment by nicoulaj** [comment]
Updated by rajkr.ch...@gmail.com on 2009-06-15T11:28:16

Our application also slow-down. When we open multiple mdi window for long time,
I checked on task manager and memory used by application keeps on increasing.

Did you get any solution for this? the solution explained above is not cleared to us.

**Comment by nicoulaj** [comment]
Updated by swi...@gmail.com on 2009-09-24T11:17:32

thanks, it was really helpful :)

**Comment by nicoulaj** [comment]
Updated by veenache...@gmail.com on 2009-10-19T07:14:26

Thanks I was able to test your fix and it works partially now. If I start with say 5 
MDI windows and remove 1. then the I have 5 objects left in the memory (even after 
forcing the garbage collector in profiler). I would expect it to have 4 objects. Then 
I tried deleting my other window and now i am left out with 4 objects. (where I would 
be expecting 3 objects).

Below is the change that I did in MDIManager.as 
                // add this event to collection for lookup in the 
effect handler
                //mgrEventCollection.addItem(mgrEvent);

```
            // listen for start and end of effect
```

mgrEvent.effect.addEventListener(EffectEvent.EFFECT_START, onMgrEffectEvent)

mgrEvent.effect.addEventListener(EffectEvent.EFFECT_END, onMgrEffectEvent);

```
            //mgrEvent.effect.play();

            var instances:Array =  mgrEvent.effect.play();
            if (instances && instances.length>0) {
                mgrEventCollection.addItem(mgrEvent);
            }
```

Please let me know if I am missing anything here.

**Comment by nicoulaj** [comment]
Updated by carlos.s...@gmail.com on 2010-11-25T18:31:31

Hello, there's any working roundtrip to this bug?
Thanks!

**Comment by nicoulaj** [comment]
Updated by carlos.s...@gmail.com on 2010-11-25T19:57:39

// Mi own solution
        private function onCloseEffectEnd(event:EffectEvent):void
        {
            var window : MDIWindow = event.effectInstance.target as MDIWindow; 
            remove(window);

// SOLUTION remove all cached effect events for the window on window close

```
        var cursor : IViewCursor = mgrEventCollection.createCursor();
        var dontMoveNext : Boolean = false;
        do {
            if (cursor.current) {
                var mgrEvent:MDIManagerEvent = cursor.current as MDIManagerEvent;
                if (mgrEvent.window === window) {
                    cursor.remove();
                    dontMoveNext = true;
                } else {
                    dontMoveNext = false;
                }
            } else {
                dontMoveNext = false;
            }
        } while (dontMoveNext || cursor.moveNext());
    }
```

**Comment by diorcety** [comment]
One solution to this problem of memory leak.
Il the effect is nothing (example new Effect()) the EFFECT_END event is never called.
So we do nothing if this case

``` actionscript
                // Play effect only if it is necessary
                if(mgrEvent.effect is CompositeEffect || (mgrEvent.effect.targets && mgrEvent.effect.targets.length))
                {
                  // add this event to collection for lookup in the effect handler
                  mgrEventCollection.addItem(mgrEvent);

                  // listen for start and end of effect
                  mgrEvent.effect.addEventListener(EffectEvent.EFFECT_START, onMgrEffectEvent)
                  mgrEvent.effect.addEventListener(EffectEvent.EFFECT_END, onMgrEffectEvent);

                  mgrEvent.effect.play();
                }
```

**Comment by nicoulaj** [comment]
OK, can you send a pull request or directly commit the fix ?
