### ISSUE TITLE
[SchedulingFramework] add entry property

### ISSUE THREAD

**Issue by alamata** [flex-users/flexlib#363]
hey,...

i would like add some description information when  clicking to scheduleViewer entry
the click function is ok but i can't get the description information

how add property to an entry

to have in example:

scheduleViewer.selectedItem.descriptioninformation

at this time i have
scheduleViewer.selectedItem.startDate
or
scheduleViewer.selectedItem.endDate
...

i have try severall mehtod by modyfing "IScheduleEntry,SimpleScheduleEntry,ColoredScheduleEntry"
but with no succes,... :((

can you provide me some help please?....

thansk for your comprehension

**Comment by alamata** [comment]
hey ,...
now everything is ok,...

i have an custom render

with

```
private function onClick():void { this.dispatchEvent(new Event(MouseEvent.CLICK, true)); }

        private function clickTest(event:MouseEvent):void { 
            trace(this.entry.startDate); 
            trace(this.entry.endDate);
            trace(this.entry.description);
            trace("Click!!"); }
```

and i have modify the IScheduleEntry and the SimpleScheduleEntry

**Comment by slangeberg** [comment]
Sorry man, I haven't looked at that framework in years. It's been abandoned,
as far as I know.

**Comment by alamata** [comment]
hey slangeberg, ;)

thx for the information,...

 i have worked around this framework and i approach the goal of the project... ;)

Waht are the modern alternative to this "old" framework,...??

**Comment by slangeberg** [comment]
I'd just write it from scratch, now. I've already implemented custom calendar for my company, just by copying and adapting CalendarLayout from adobe flex.
